# Generated by Django 5.1.4 on 2025-01-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=7)),
                ('byr', models.FloatField(blank=True, null=True)),
                ('usd', models.FloatField(blank=True, null=True)),
                ('eur', models.FloatField(blank=True, null=True)),
                ('kzt', models.FloatField(blank=True, null=True)),
                ('uah', models.FloatField(blank=True, null=True)),
                ('azn', models.FloatField(blank=True, null=True)),
                ('kgs', models.FloatField(blank=True, null=True)),
                ('uzs', models.FloatField(blank=True, null=True)),
                ('gel', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'db_table': 'currency_table',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SkillByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillsBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('key_skills', models.TextField(verbose_name='Ключевые навыки')),
                ('salary_from', models.CharField(default=None, max_length=255, null=True)),
                ('salary_to', models.CharField(default=None, max_length=255, null=True)),
                ('salary_currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('area_name', models.CharField(max_length=255, verbose_name='Город')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
            },
        ),
    ]
