# Generated by Django 5.1.4 on 2025-01-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('key_skills', models.TextField(verbose_name='Ключевые навыки')),
                ('salary_from', models.FloatField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.FloatField(blank=True, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('area_name', models.CharField(max_length=255, verbose_name='Город')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
