# Generated by Django 5.1.4 on 2025-01-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=7)),
                ('byr', models.FloatField(blank=True, null=True)),
                ('usd', models.FloatField(blank=True, null=True)),
                ('eur', models.FloatField(blank=True, null=True)),
                ('kzt', models.FloatField(blank=True, null=True)),
                ('uah', models.FloatField(blank=True, null=True)),
                ('azn', models.FloatField(blank=True, null=True)),
                ('kgs', models.FloatField(blank=True, null=True)),
                ('uzs', models.FloatField(blank=True, null=True)),
                ('gel', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'db_table': 'currency_table',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelTable(
            name='vacancy',
            table='vacancy_table',
        ),
    ]
