# Generated by Django 5.1.4 on 2025-01-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('salary', models.IntegerField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Средняя зарплата',
                'verbose_name_plural': 'Средняя зарплата',
                'db_table': 'average_salary',
            },
        ),
        migrations.CreateModel(
            name='BackendAverageSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('salary', models.IntegerField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Средняя зарплата Backend',
                'verbose_name_plural': 'Средняя зарплата Backend',
                'db_table': 'backend_average_salary',
            },
        ),
        migrations.CreateModel(
            name='BackendVacancyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('vacancy_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Кол-во вакансий Backend',
                'verbose_name_plural': 'Кол-во вакансий Backend',
                'db_table': 'backend_vacancy_statistic',
            },
        ),
        migrations.CreateModel(
            name='FormattedVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=255, null=True)),
                ('salary', models.CharField(default=None, max_length=255, null=True)),
                ('area_name', models.TextField(default=None, null=True)),
                ('published_at', models.DateTimeField(default=None)),
            ],
            options={
                'verbose_name': 'Отформатированные вакансии',
                'verbose_name_plural': 'Отформатированные вакансии',
                'db_table': 'formatted_vacancies',
            },
        ),
        migrations.CreateModel(
            name='PartArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('percentage', models.FloatField()),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам',
                'verbose_name_plural': 'Доля вакансий по городам',
                'db_table': 'part_area',
            },
        ),
        migrations.CreateModel(
            name='PartAreaBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('percentage', models.FloatField()),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам для Backend',
                'verbose_name_plural': 'Доля вакансий по городам для Backend',
                'db_table': 'part_area_backend',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('average_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам',
                'verbose_name_plural': 'Уровень зарплат по городам',
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='SalaryBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('average_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам',
                'verbose_name_plural': 'Уровень зарплат по городам',
                'db_table': 'salary_backend',
            },
        ),
        migrations.CreateModel(
            name='SkillsBackendByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VacancyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('vacancy_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Кол-во вакансий',
                'verbose_name_plural': 'Кол-во вакансий',
                'db_table': 'vacancy_statistic',
            },
        ),
    ]
