# Generated by Django 5.1.4 on 2025-01-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_averagesalary_backendaveragesalary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormattedVacancyAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=255, null=True)),
                ('salary', models.CharField(default=None, max_length=255, null=True)),
                ('area_name', models.TextField(default=None, null=True)),
                ('published_at', models.DateTimeField(default=None)),
            ],
            options={
                'verbose_name': 'Все отформатированные вакансии',
                'verbose_name_plural': 'Все отформатированные вакансии',
                'db_table': 'all_formatted_vacancies',
            },
        ),
    ]
