# Generated by Django 5.1.4 on 2025-01-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formattedvacancyall'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillByYearSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='salarybackend',
            options={'verbose_name': 'Уровень зарплат по городам по Backend', 'verbose_name_plural': 'Уровень зарплат по городам по Backend'},
        ),
    ]
