# Generated by Django 5.1.4 on 2025-01-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvgSalaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('average_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Статистика по средней зарплате',
                'verbose_name_plural': 'Статистика по средней зарплате',
                'db_table': 'avg_salary_stats',
            },
        ),
        migrations.CreateModel(
            name='BackendAvgSalaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('backend_average_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Статистика по средней зарплате Backend-программистов',
                'verbose_name_plural': 'Статистика по средней зарплате Backend-программистов',
                'db_table': 'backend_avg_salary_stats',
            },
        ),
        migrations.CreateModel(
            name='BackendStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('backend_vacancy_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Статистика по Backend-программистам',
                'verbose_name_plural': 'Статистика по Backend-программистам',
                'db_table': 'backend_stats',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=7)),
                ('byr', models.FloatField(blank=True, null=True)),
                ('usd', models.FloatField(blank=True, null=True)),
                ('eur', models.FloatField(blank=True, null=True)),
                ('kzt', models.FloatField(blank=True, null=True)),
                ('uah', models.FloatField(blank=True, null=True)),
                ('azn', models.FloatField(blank=True, null=True)),
                ('kgs', models.FloatField(blank=True, null=True)),
                ('uzs', models.FloatField(blank=True, null=True)),
                ('gel', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'db_table': 'currency',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DolyaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('vacancy_percentage', models.FloatField()),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам',
                'verbose_name_plural': 'Доля вакансий по городам',
                'db_table': 'dolya_area',
            },
        ),
        migrations.CreateModel(
            name='DolyaAreaBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('vacancy_percentage', models.FloatField()),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам для бэкендера',
                'verbose_name_plural': 'Доля вакансий по городам для бэкендера',
                'db_table': 'dolya_area_backend',
            },
        ),
        migrations.CreateModel(
            name='ProcessedVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('salary', models.IntegerField(default=None, null=True)),
                ('area_name', models.TextField(default=None, null=True)),
                ('published_at', models.DateTimeField(default=None)),
            ],
            options={
                'verbose_name': 'Обработанная вакансия',
                'verbose_name_plural': 'Обработанные вакансии',
                'db_table': 'processed_vacancies',
            },
        ),
        migrations.CreateModel(
            name='SalaryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('average_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам',
                'verbose_name_plural': 'Уровень зарплат по городам',
                'db_table': 'salary_area',
            },
        ),
        migrations.CreateModel(
            name='SalaryAreaBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('average_salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам для бэкендера',
                'verbose_name_plural': 'Уровень зарплат по городам для бэкендера',
                'db_table': 'salary_area_backend',
            },
        ),
        migrations.CreateModel(
            name='VacancyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('vacancy_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Статистика по количеству вакансий',
                'verbose_name_plural': 'Статистика по количеству вакансий',
                'db_table': 'vacancy_stats',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, null=True)),
                ('key_skills', models.TextField(default=None, null=True)),
                ('salary_from', models.IntegerField(default=None, null=True)),
                ('salary_to', models.IntegerField(default=None, null=True)),
                ('salary_currency', models.CharField(default=None, max_length=10, null=True)),
                ('area_name', models.TextField(default=None, null=True)),
                ('published_at', models.DateTimeField(default=None)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
                'indexes': [models.Index(fields=['name'], name='name_idx')],
            },
        ),
    ]
